# Generated by Django 6.1.1 on 2026-09-22 07:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "industry",
                    models.CharField(
                        help_text="Groups use cases in the picker, e.g. Banking.",
                        max_length=60,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="One line shown under the name.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What the workflow is, in business terms."
                    ),
                ),
                (
                    "business_value",
                    models.TextField(
                        blank=True,
                        help_text="Why an executive should care: cost, speed, risk, revenue.",
                    ),
                ),
                (
                    "input_label",
                    models.CharField(
                        default="Customer message",
                        help_text="Label above the text box.",
                        max_length=80,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active use cases appear in the demo.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("answers", models.JSONField()),
                ("decision", models.CharField(max_length=20)),
                (
                    "model_ms",
                    models.FloatField(help_text="Time spent inside the model."),
                ),
                ("input_tokens", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "use_case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classifier.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short chip label, e.g. Duplicate charge.",
                        max_length=60,
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="classifier.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Machine name, e.g. department.", max_length=60
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name, e.g. Department.", max_length=80
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("choice", "Choice: pick one label"),
                            ("score", "Score: place on an ordered scale"),
                            ("noul", "Yes / No: probability a statement holds"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.CharField(
                        help_text="The question the model answers.", max_length=300
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="One option per line.<br><b>Choice</b>: <code>label: description</code>. Say what the label covers and how it differs from its neighbours.<br><b>Score</b>: one level per line, lowest first.<br><b>Yes / No</b>: optional <code>true: description</code> and <code>false: description</code> lines.",
                    ),
                ),
                (
                    "min_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Automation gate. When this field's confidence falls below this value, the decision goes to human review. Leave blank for fields that shouldn't block automation.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="classifier.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("use_case", "key"), name="unique_field_key_per_use_case"
                    )
                ],
            },
        ),
    ]
