# Generated by Django 6.1.1 on 2026-09-22 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0002_seed_use_cases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="min_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Automation gate. When this field's confidence falls below this value, the decision escalates to System 2 (an LLM or a person). Leave blank for fields that shouldn't block automation.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
